name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.ARTIFACTORY_URL }}/nginx:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ARTIFACTORY_URL }}/nginx:latest
