name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-nginx-image:latest .

    - name: Save Docker image as a tar file
      run: |
        docker save my-nginx-image:latest -o my-nginx-image.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: my-nginx-image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: docker-image

    - name: Push Docker image to JFrog
      env:
        JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        JFROG_URL: ${{ secrets.JFROG_URL }}
      run: |
        # Extract the downloaded artifact
        tar -xvf docker-image

        # Push the Docker image tar file using curl
        curl -uadmin:${{ secrets.JFROG_PASSWORD }} -T my-nginx-image.tar "${{ secrets.JFROG_URL }}/artifactory/example-repo-local/my-nginx-image.tar"
