name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify access with curl
        run: curl -H "ngrok-skip-browser-warning:true" -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }} ${{ secrets.ARTIFACTORY_URL }}/api/system/ping

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ARTIFACTORY_URL }}/my-repo/nginx:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ARTIFACTORY_URL }}/my-repo/nginx:latest
