name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-nginx-image:latest .

  #   - name: Save Docker image as a tar file
  #     run: |
  #       docker save my-nginx-image:latest -o my-nginx-image.tar

  #   - name: Upload Docker image artifact
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: docker-image
  #       path: my-nginx-image.tar

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Download Docker image artifact
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: docker-image
  #       path: my-nginx-image.tar

    - name: Push Docker image to ARTIFACTORY
      env:
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      run: |
        # Push the Docker image tar file using curl
        curl -uadmin:${{ secrets.ARTIFACTORY_PASSWORD }} -T my-nginx-image:latest "${{ secrets.ARTIFACTORY_URL }}/artifactory/example-repo-local/my-nginx-image:latest"
