name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Check Docker status
        run: systemctl status docker

      - name: Restart Docker daemon
        run: sudo systemctl restart docker

      - name: Log in to JFrog Artifactory
        run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login -u "${{ secrets.JFROG_USERNAME }}" --password-stdin "${{ secrets.JFROG_REGISTRY }}"

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.JFROG_REGISTRY }}/mydemo-docker-jfrog-repo/my-nginx-image:latest .
          docker push ${{ secrets.JFROG_REGISTRY }}/mydemo-docker-jfrog-repo/my-nginx-image:latest
